### ISSUE TITLE
Demo里面有所有的书了，家长账号里面进入去看孩子记录的时候里面还有书

### ISSUE THREAD

**Issue by Jennyhym** [JGTM2021/MentorA2Z#27]

**Comment by JGTM2021** [comment]
这个没看懂，把事儿再试着说清楚点儿哈，嘿嘿

**Comment by JGTM2021** [comment]
意思是书目重复了吗？

1、以后不一定内置 Demo 账号，这样没有孩子账号的就没书看；
2、如果确实没有孩子账号，提供 Demo 账号这样家长也能看到书目，考虑是否给孩子申请一个 Kids A-Z 账号；
3、孩子账号进入看到的书，就是孩子账号能看到的书（目前没有 Demo 的全，也没准以后 Demo 不提供这么多书）；
4、孩子账号进入可以显示孩子看过哪些书、每个模块（比如字母书）的完成比例，还有多少书目孩子还没有看过……
5、孩子账号进入可以下载孩子在书目上的录音，显示和打印孩子的涂鸦等等

总之，Demo 是个“假孩子”，主要是测试和演示时使用的。

**Comment by Jennyhym** [comment]
哈哈，是这个意思。喔喔。懂了。哈哈哈



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年9月19日(周日) 上午10:50
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [JGTM2021/MentorA2Z] Demo里面有所有的书了，家长账号里面进入去看孩子记录的时候里面还有书 (#27)




 
意思是书目重复了吗？
 
1、以后不一定内置 Demo 账号，这样没有孩子账号的就没书看；
 2、如果确实没有孩子账号，提供 Demo 账号这样家长也能看到书目，考虑是否给孩子申请一个 Kids A-Z 账号；
 3、孩子账号进入看到的书，就是孩子账号能看到的书（目前没有 Demo 的全，也没准以后 Demo 不提供这么多书）；
 4、孩子账号进入可以显示孩子看过哪些书、每个模块（比如字母书）的完成比例，还有多少书目孩子还没有看过……
 5、孩子账号进入可以下载孩子在书目上的录音，显示和打印孩子的涂鸦等等
 
总之，Demo 是个“假孩子”，主要是测试和演示时使用的。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
